name: CI/CD to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Test
        run: npx ng test --watch=false --browsers=ChromeHeadless

      - name: Build
        run: npx ng build --base-href=/Angular_E-com_WebApp/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/Angular_E-com_WebApp/browser
